[package]
name = "prime_sieves"
version = "0.1.0"
authors = ["Szymon Zimnowoda <szimnowoda@kymetacorp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
